export default class AyCarousel {
    static documentStyleAdded: boolean;
    offset: any;
    startX: number;
    startY: number;
    initialIndex: number;
    initialIndexSetOnce: boolean;
    delta: any;
    position: any;
    currentTranslate: number;
    lastTranslate: number;
    callbacks: any;
    cards: HTMLElement[];
    cardWidth: number;
    index: number;
    carousel: HTMLElement;
    dotContainer: HTMLUListElement;
    dots: HTMLLIElement[];
    totalMove: any;
    lastPos: any;
    amplitude: any;
    velocity: any;
    frame: any;
    timestamp: number;
    previousTranslate: number;
    target: any;
    closestCard: any;
    velocityInterval: any;
    config: any;
    viewportWidth: any;
    carouselParent: any;
    destroyed: boolean;
    constructor(carousel: HTMLElement, config?: any, initialIndex?: number);
    updateItems(): void;
    handleResize(snap?: boolean): void;
    onDragStart(e: any): void;
    calcVelocity(): number;
    momentumScroll(stopPoint: any): void;
    onDragMove(e: any): void;
    calculateIndex(position?: any): number;
    onDotClick(e: any): void;
    onDotKey(e: any): void;
    setIndex(index: number): void;
    snap(nextIndex?: number, direction?: string): void;
    onDragEnd(e: any): void;
    translate(x: number, length: number, fn?: string, updateIndex?: boolean): void;
    percentVisible(card: HTMLElement): number;
    rescale(): void;
    calcOS(i: any): number;
    cleanUp(): void;
    removeDots(includingContainer?: boolean): void;
    setupConfig(config?: any): any;
}
